baseURL = "https://example.com"
title = "Eichhornbau"
author = "username"
languageCode = "de"
DefaultContentLanguage = "de"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['home']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "EB Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Tella"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Dein Dienstleister für Bau- und Baumanagement"
    meta_og_title = "Eichhornbau"
    meta_og_type = "website"
    meta_og_url = "https://eichhornbau.de"
    meta_og_description = "Dein Dienstleister für Bau- und Baumanagement"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Leistungen"
    url = "/leistungen/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "Über Mich"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Start"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
